### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [bastilian/validcode-textmate-bundles#1]
I would like to use your lexer at [github/linguist](https://github.com/github/linguist) to highlight Liquid code on GitHub but I don't know what licensing terms you're distributing it under.
Any chance you could pick one from here: http://choosealicense.com?

**Comment by bastilian** [comment]
@pchaigno i've added the MIT license. feel free to use any part of it. :)

**Comment by pchaigno** [comment]
@bastilian Thanks!
